### ISSUE TITLE
NoSuchMethodError using Gson in KSP plugin on Kotlin 1.9

### ISSUE THREAD

**Issue by jbarr21** [bazelbuild/rules_kotlin#1012]
Using a KSP processor that makes use of Gson works fine with master of rules_kotlin & Kotlin 1.8, but if you patch #996 and use Kotlin 1.9, then your build will fail with NoSuchMethodError likely in part due to [youtrack/KT-61147](https://youtrack.jetbrains.com/issue/KT-61147/Kotlin-Compiler-1.9.0-bundles-a-stripped-unshadowed-version-of-Gson). The method that isn't found in Gson has [existed for a long time](https://github.com/google/gson/blame/c5c1fbf9a12def0b3b5e6c6e84c36b185dfb4628/gson/src/main/java/com/google/gson/Gson.java#L795).

If you debug the KSP action & put a breakpoint in the KSP processor's call to Gson(), you can see that the Gson class is loaded from the `kotlin-compiler.jar` jar by evaluating `Gson::class.java.getResource("")` which yields:
```
jar:file:/private/var/tmp/_bazel_jbarr/bcfe5339f0a44b000844f91ba388ad2b/execroot/__main__/bazel-out/host-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_kotlin/src/main/kotlin/build.runfiles/com_github_jetbrains_kotlin/lib/kotlin-compiler.jar!/com/google/gson/
```

While the compiler shouldn't have a non-shadowed version of Gson, the other part of this issue is that the `kotlin-compiler.jar` shouldn't be on KSP's apclasspath. A `bazel aquery //:coffee_lib` shows that the processorpath (and thus ksp's apclasspath) does not contain the `kotlin-compiler.jar`, so why was the Gson class loaded from the compiler jar?

REPRO ([branch](https://github.com/bazelbuild/rules_kotlin/compare/master...jbarr21:rules_kotlin:jb/kt-19-ksp-gson)):
```
git clone https://github.com/jbarr21/rules_kotlin.git
git checkout jb/kt-19-ksp-gson
cd examples/ksp
bazel build //:coffee_lib
```

EXPECTED:
- Successful compilation

ACTUAL:
- `[Build error](exception: java.lang.NoSuchMethodError: 'void com.google.gson.Gson.toJson(java.lang.Object, java.lang.Appendable))`

```
ERROR: /Users/jbarr/Uber/rules_kotlin/examples/ksp/BUILD:56:15: KotlinKsp //:coffee_lib { kt: 1, java: 0, srcjars: 0 } for darwin_arm64 failed: (Exit 1): build failed: error executing command (from target //:coffee_lib) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_kotlin/src/main/kotlin/build '--flagfile=bazel-out/darwin_arm64-fastbuild/bin/coffee_lib-ksp-kt-gensrc.jar-0.params'
exception: java.lang.NoSuchMethodError: 'void com.google.gson.Gson.toJson(java.lang.Object, java.lang.Appendable)'
	at coffee.proc.CoffeeProcessor.process(CoffeeProcessor.kt:16)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:305)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:303)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:409)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:303)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at io.bazel.kotlin.compiler.BazelK2JVMCompiler.exec(BazelK2JVMCompiler.kt:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.bazel.kotlin.builder.toolchain.KotlinToolchain$KotlinCliToolInvoker.compile(KotlinToolchain.kt:213)
	at io.bazel.kotlin.builder.tasks.jvm.CompilationTaskKt$runKspPlugin$1$1$1.invoke(CompilationTask.kt:286)
	at io.bazel.kotlin.builder.tasks.jvm.CompilationTaskKt$runKspPlugin$1$1$1.invoke(CompilationTask.kt:286)
	at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.executeCompilerTask(CompilationTaskContext.kt:126)
	at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.executeCompilerTask$default(CompilationTaskContext.kt:118)
	at io.bazel.kotlin.builder.tasks.jvm.CompilationTaskKt$runKspPlugin$1.invoke(CompilationTask.kt:284)
	at io.bazel.kotlin.builder.tasks.jvm.CompilationTaskKt$runKspPlugin$1.invoke(CompilationTask.kt:278)
	at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.execute(CompilationTaskContext.kt:153)
	at io.bazel.kotlin.builder.toolchain.CompilationTaskContext.execute(CompilationTaskContext.kt:145)
	at io.bazel.kotlin.builder.tasks.jvm.CompilationTaskKt.runKspPlugin(CompilationTask.kt:278)
	at io.bazel.kotlin.builder.tasks.jvm.CompilationTaskKt.runPlugins(CompilationTask.kt:233)
	at io.bazel.kotlin.builder.tasks.jvm.KotlinJvmTaskExecutor.execute(KotlinJvmTaskExecutor.kt:52)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.executeJvmTask(KotlinBuilder.kt:210)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.build(KotlinBuilder.kt:103)
	at io.bazel.kotlin.builder.tasks.CompileKotlin.invoke(CompileKotlin.kt:27)
	at io.bazel.worker.PersistentWorker$workTo$1.invoke(PersistentWorker.kt:97)
	at io.bazel.worker.PersistentWorker$workTo$1.invoke(PersistentWorker.kt:97)
	at io.bazel.worker.WorkerContext$TaskContext.resultOf(WorkerContext.kt:128)
	at io.bazel.worker.WorkerContext.doTask(WorkerContext.kt:156)
	at io.bazel.worker.PersistentWorker$start$1$1$producer$1$1.invoke$lambda$0(PersistentWorker.kt:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Aug 15, 2023 5:16:58 PM worker request 0
SEVERE: Compilation failure: compile phase failed:Target //:coffee_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.788s, Critical Path: 0.05s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by jbarr21** [comment]
[Kotlin 1.9.10](https://github.com/JetBrains/kotlin/releases/tag/v1.9.10) resolves this issue
