### ISSUE TITLE
rules_kotlin breakage on Bazel CI

### ISSUE THREAD

**Issue by jin** [bazelbuild/rules_kotlin#105]
```
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-w9pz-1/bazel-downstream-projects/rules_kotlin/tests/integrationtests/jvm/basic/BUILD:101:1: Couldn't build file tests/integrationtests/jvm/basic/test_friends_library.jar: Compiling Kotlin //tests/integrationtests/jvm/basic:test_friends_library { kt: 1, java: 0, srcjars: 0 } failed (Exit 1): builder failed: error executing command
--
  | (cd /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/39debe0ec575e8516eeb1a26933a8f6b/execroot/io_bazel_rules_kotlin && \
  | exec env - \
  | bazel-out/host/bin/external/io_bazel_rules_kotlin/kotlin/builder/builder '--flagfile=bazel-out/k8-fastbuild/bin/tests/integrationtests/jvm/basic/test_friends_library.jar-0.params')
  | ERROR: Worker threw uncaught exception with args: --flagfile=bazel-out/k8-fastbuild/bin/tests/integrationtests/jvm/basic/test_friends_library.jar-0.params
  | java.lang.IllegalStateException: unknown flag file format for bazel-out/k8-fastbuild/bin/tests/integrationtests/jvm/basic/test_friends_library.jar-0.params
  | at io.bazel.kotlin.builder.tasks.KotlinBuilder.execute(KotlinBuilder.kt:48)
  | at io.bazel.kotlin.builder.tasks.KotlinBuilder.apply(KotlinBuilder.kt:89)
  | at io.bazel.kotlin.builder.tasks.BazelWorker.runAsPersistentWorker(BazelWorker.kt:88)
  | at io.bazel.kotlin.builder.tasks.BazelWorker.apply(BazelWorker.kt:67)
  | at io.bazel.kotlin.builder.KotlinBuilderMain.main(KotlinBuilderMain.java:29)
```

14.04: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/371#1464a8d4-1938-4f81-991e-94faa51dfc93
16.04: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/371#feda06be-6a26-4b85-9fa0-535a74441ce7
macOS: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/371#77a386ca-307a-443d-9b1a-fa74b427f993

Latest passing nightly was on Friday: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/368

**Comment by hsyed** [comment]
Fixed.
