### ISSUE TITLE
kt_jvm_test is incompatible with Java >= 18

### ISSUE THREAD

**Issue by josephglanville** [bazelbuild/rules_kotlin#1100]
Because of deprecation of the Security Manager APIs becoming an error in Java 18 `kt_jvm_test` will fail with the following error:
```
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.installSecurityManager(JUnit4Runner.java:256)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:113)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
```

This can be worked around by specifying the appropriate JVM flags in `.bazelrc`:
```
common --jvmopt=-Djava.security.manager=allow
```

The correct fix however would be to port across the change made to the upstream Java test rule and read the runtime version from `JavaRuntimeInfo` and conditionally set the appropriate JVM option, see the Bazel issue for more details including the linked fix commit: https://github.com/bazelbuild/bazel/issues/16421

**Comment by restingbull** [comment]
Need to update to junit5 as the default.
