### ISSUE TITLE
[Bazel CI] Error Generating proto for Starlark doc for core failed with Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_kotlin#1182]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3934#019033d2-a3c8-4c92-837d-b29b9817cdf0

 Platform: Ubuntu

 Logs: 
```
 ERROR: /var/lib/buildkite-agent/builds/bk-docker-v4r8/bazel-org-repo-root/rules_kotlin/kotlin/BUILD:39:12: Generating proto for Starlark doc for core failed: (Exit 1): core_stardoc failed: error executing Stardoc command (from target //kotlin:core)
 

com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: File /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d4e8137e50b044619ec9686d4fc6cc5a/sandbox/linux-sandbox/272/execroot/rules_kotlin/bazel-out/k8-opt-exec-ST-a828a81199fe/bin/kotlin/core_stardoc.runfiles/rules_java_builtin/toolchains/toolchain_utils.bzl imported '//java/common:java_common.bzl', yet /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d4e8137e50b044619ec9686d4fc6cc5a/sandbox/linux-sandbox/272/execroot/rules_kotlin/bazel-out/k8-opt-exec-ST-a828a81199fe/bin/kotlin/core_stardoc.runfiles/rules_java_builtin/java/common/java_common.bzl was not found.
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:454)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:450)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:450)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:450)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:450)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:450)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:289)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:151)
Caused by: java.nio.file.NoSuchFileException: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d4e8137e50b044619ec9686d4fc6cc5a/sandbox/linux-sandbox/272/execroot/rules_kotlin/bazel-out/k8-opt-exec-ST-a828a81199fe/bin/kotlin/core_stardoc.runfiles/rules_java_builtin/java/common/java_common.bzl
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:429)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:450)
	... 7 more
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_kotlin
git reset 7dcb7f94f3f367110d75a3ea4464ae4e4cbbf8f0  --hard
export USE_BAZEL_VERSION=880c17c67a9b4e17e9753a5c6e2a759bff5a2cfe
bazel test //:all_tests 
 ``` 
 CC Greenteam @mai93

**Comment by sgowroji** [comment]
CC @Bencodes

**Comment by restingbull** [comment]
Appears to be CI specific -- works on MacOS.
