### ISSUE TITLE
Unable to use kotlin_rules as a local dir or as git override due to `NoClassDefFoundError: dagger/internal/Factory`

### ISSUE THREAD

**Issue by develar** [bazelbuild/rules_kotlin#1235]
If I use

```
git_override(
  module_name = "rules_kotlin",
  remote = "https://github.com/bazelbuild/rules_kotlin.git",
  commit = "40fecf58b5e6b6002c137fca7ea91c7cb4b5889b"
)
```

or 

```
local_path_override(
  module_name = "rules_kotlin",
  path = "../rules_kotlin",
)
```

I get

```
Exception in thread "main" java.lang.NoClassDefFoundError: dagger/internal/Factory
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at io.bazel.kotlin.builder.DaggerJdepsMergerComponent$JdepsMergerComponentImpl.work(DaggerJdepsMergerComponent.java:48)
	at io.bazel.kotlin.builder.cmd.MergeJdeps$main$1.invoke(MergeJdeps.kt:29)
	at io.bazel.kotlin.builder.cmd.MergeJdeps$main$1.invoke(MergeJdeps.kt:28)
	at io.bazel.worker.Worker$Companion.from(Worker.kt:32)
	at io.bazel.kotlin.builder.cmd.MergeJdeps.main(MergeJdeps.kt:28)
Caused by: java.lang.ClassNotFoundException: dagger.internal.Factory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 14 more
```

I tried to add runtime dependency on Dagger to various places, but still doesn't work.

```
Index: src/main/kotlin/io/bazel/kotlin/builder/cmd/BUILD.bazel
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/kotlin/io/bazel/kotlin/builder/cmd/BUILD.bazel b/src/main/kotlin/io/bazel/kotlin/builder/cmd/BUILD.bazel
--- a/src/main/kotlin/io/bazel/kotlin/builder/cmd/BUILD.bazel	(revision c93d6ae990a1d063f0a4e6fbef7447af2799f661)
+++ b/src/main/kotlin/io/bazel/kotlin/builder/cmd/BUILD.bazel	(date 1730963265547)
@@ -50,6 +50,7 @@
     runtime_deps = [
         ":build_lib",
         "@bazel_tools//tools/jdk:JacocoCoverage",
+        "@kotlin_rules_maven//:com_google_dagger_dagger",
     ],
 )
 
@@ -71,5 +72,5 @@
     main_class = "io.bazel.kotlin.builder.cmd.MergeJdeps",
     shade_rules = "//src/main/kotlin:shade.jarjar",
     visibility = ["//src:__subpackages__"],
-    runtime_deps = [":merge_jdeps_lib"],
+    runtime_deps = [":merge_jdeps_lib", "@kotlin_rules_maven//:com_google_dagger_dagger"],
 )
```

The same is reproduced on another machine. Clearing the cache doesn't help.

**Comment by develar** [comment]
There is a rule `rule dagger.** io.bazel.kotlin.builder.dagger.@1` in `rules_kotlin/src/main/kotlin/shade.jarjar`. However, for some reason, shading doesn’t seem to be performed correctly.

**Comment by restingbull** [comment]
This is not currently supported, as `rules_kotlin` packages release artifacts to reduce the download footprint and dependencies.

See the [Development Setup Guide](https://github.com/bazelbuild/rules_kotlin/blob/master/README.md#development-setup-guide) for local development.

**Comment by develar** [comment]
How can I help make this possible? This complication seems unnecessary to me. Am I correct in understanding that we can’t simplify the project for now because we still need to support the old `WORKSPACE`?
