### ISSUE TITLE
Implicit dependency issue

### ISSUE THREAD

**Issue by menny** [bazelbuild/rules_kotlin#140]
I think something is wrong with my setup, any help would be appreciated. I get this error when I try to build my Kotlin targets:
```
INFO: SHA256 (https://github.com/bazelbuild/rules_kotlin/archive/c56299c32437cf9608612868beb1c2ba9386940d.zip) = 160e06a8d0a32b07b1c8ec4c88c9fd42988c3a4d4ba43776a87dbba99634f67e
ERROR: /Users/menny/dev/spotify/client-android/bazel/transformer/BUILD.bazel:17:1: every rule of type kt_jvm_binary implicitly depends upon the target '@com_github_jetbrains_kotlin//:kotlin-runtime', but this target could not be found because of: no such package '@com_github_jetbrains_kotlin//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 59, in workspace_and_buildfile
		ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //kotlin/internal/repositories:BUILD.com_github_jetbrains_kotlin: not found.
ERROR: Analysis of target '//bazel/transformer:transformer' failed; build aborted: no such package '@com_github_jetbrains_kotlin//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 59, in workspace_and_buildfile
		ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //kotlin/internal/repositories:BUILD.com_github_jetbrains_kotlin: not found.
INFO: Elapsed time: 6.004s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded)
FAILED: Build did NOT complete successfully (10 packages loaded)
```

In my `WORKSPACE` file I've setup Kotlin like this:
```
rules_kotlin_version = "c56299c32437cf9608612868beb1c2ba9386940d"

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()
```

**Comment by menny** [comment]
I'm on Mac - High Sierra v10.13.6 (17G65) - using Bazel 0.16.1 from brew (Google's tap).

**Comment by menny** [comment]
I tried `bazel clean --expunge`.
I tried running in sandbox or with `--spawn_strategy=standalone`

Same error every time.

**Comment by menny** [comment]
I have https://github.com/bazelbuild/rules_kotlin/pull/141 which seems to fix the issue.

**Comment by hsyed** [comment]
Strange. do you have persistent workers enabled ? 

I have been trying to get rid of the `@io_bazel_rules_kotlin` references.

**Comment by hsyed** [comment]
Does `@//kotlin/internal/repositories:BUILD.com_github_jetbrains_kotlin` work ?

**Comment by Pmcneice** [comment]
I also have the same error using the most recent commit

**Comment by hsyed** [comment]
@Pmcneice do you have workers enabled ?

**Comment by hsyed** [comment]
They aren't enabled by default -- I have an issue open in bazel core as for Kotlin it makes no sense to run without workers.

lets see if that fixes your problem, I'll update the readme to make it clearer if it does.

**Comment by menny** [comment]
@hsyed changing to `build_file = "@//kotlin/internal/repositories:BUILD.com_github_jetbrains_kotlin"` did not fix the issue:
```
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/menny/rules_kotlin/archive/e303a5506ed3a6e7c61cbc9f41a8c97be8fe5c08.zip) = c48c7b8823ab288dd32b1ec5081902525583b10f6dd99f63939a0a8f7ef19f92
ERROR: /Users/menny/dev/spotify/client-android/bazel/transformer/BUILD.bazel:17:1: every rule of type kt_jvm_binary implicitly depends upon the target '@com_github_jetbrains_kotlin//:kotlin-runtime', but this target could not be found because of: no such package '@com_github_jetbrains_kotlin//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 59, in workspace_and_buildfile
		ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //kotlin/internal/repositories:BUILD.com_github_jetbrains_kotlin: not found.
ERROR: Analysis of target '//bazel/transformer:transformer' failed; build aborted: no such package '@com_github_jetbrains_kotlin//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_menny/abbd8cf9e5bbd5870afa5547369aa515/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 59, in workspace_and_buildfile
		ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Unable to load package for //kotlin/internal/repositories:BUILD.com_github_jetbrains_kotlin: not found.
INFO: Elapsed time: 6.368s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded)
FAILED: Build did NOT complete successfully (10 packages loaded)
```

See https://github.com/bazelbuild/rules_kotlin/pull/141/commits/e303a5506ed3a6e7c61cbc9f41a8c97be8fe5c08
