### ISSUE TITLE
Cannot run project with kotlin classes

### ISSUE THREAD

**Issue by Kadanza** [bazelbuild/rules_kotlin#149]
I try run java project with kotlin files in android studio, but got error.

```
ERROR: /Users/olegBorisenkov/Desktop/examples-master/android/firebase-cloud-messaging/app/BUILD:10:1: Building app/libapp.jar (3 source files) failed (Exit 1).
app/src/main/java/com/example/myapplication/MainActivity.java:18: error: cannot find symbol
        new Test().Main();
            ^
  symbol:   class Test
  location: class MainActivity
```

![2018-09-19 11 25 19](https://user-images.githubusercontent.com/35968229/45740810-c1a98600-bbfe-11e8-8470-2c38fd7b0f15.png)

When I convert my Activity class  from java to kotlin I don't see R class

![2018-09-19 11 28 41](https://user-images.githubusercontent.com/35968229/45740996-34b2fc80-bbff-11e8-9ed4-f406a1e823be.png)

My BUILD File

```
load("@tools_android//tools/googleservices:defs.bzl", "google_services_xml")
load("@gmaven_rules//:defs.bzl", "gmaven_artifact")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

GOOGLE_SERVICES_XML = google_services_xml(
    package_name = "com.example.myapplication",
    google_services_json = "google-services.json"
)

android_binary(
    name = "app",
    srcs = glob(["src/main/java/**/*.java"]),
    manifest = "src/main/AndroidManifest.xml",
    resource_files = glob(["src/main/res/**"]),

    # this sets the java package for the R class, since this android_binary
    # rule isn't under a java root (i.e., some directory named "java" for the
    # root of the java code for the app).
    custom_package = "com.example.myapplication",

    deps = [


        gmaven_artifact("com.google.firebase:firebase_messaging:aar:17.0.0"),
        gmaven_artifact("com.google.firebase:firebase_iid:aar:16.0.0"),
        gmaven_artifact("com.android.support:appcompat_v7:aar:26.1.0"),
        gmaven_artifact("com.android.support.constraint:constraint_layout:aar:1.0.2"),
        "@com_google_guava_guava//jar",
        #"@com_android_volley_volley//jar"

    ],
    manifest_values = {
      "minSdkVersion": "21",
      "applicationId": "com.example.myapplication",
    }
)
```

My WORKSPACE  File

```

android_sdk_repository(
	name = "androidsdk",
	api_level = 28,
	# Replace with path to Android SDK on your system
	path = "/Users/olegBorisenkov/Library/Android/sdk/",
)


GMAVEN_TAG = "20180530-1"
http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://github.com/bazelbuild/gmaven_rules/archive/%s.tar.gz" % GMAVEN_TAG,
)


load("@gmaven_rules//:gmaven.bzl", "gmaven_rules")
gmaven_rules()

TOOLS_ANDROID_COMMIT = "0e864ba5a86958513658250de587416d8e17c481"
http_archive(
  name = "tools_android",
  strip_prefix = "tools_android-" + TOOLS_ANDROID_COMMIT,
  url = "https://github.com/bazelbuild/tools_android/archive/%s.tar.gz" % TOOLS_ANDROID_COMMIT,
)
load("@tools_android//tools/googleservices:defs.bzl", "google_services_workspace_dependencies")
google_services_workspace_dependencies()


maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0"
)

maven_jar(
    name = "com_android_volley_volley",
    artifact = "com.android.volley:volley:1.1.0"
)



rules_kotlin_version = "67f4a6050584730ebae7f8a40435a209f8e0b48e"

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()
```

**Comment by hsyed** [comment]
I don't see `kt_android_library` used above.

**Comment by Kadanza** [comment]
@hsyed 
I use now project for test, what has _kt_android_library_ 
From https://github.com/Pmcneice/AndroidBazelExample

I've  got error 
```

ERROR: C:/users/dmitry/desktop/projects/androidbazelexample/app/BUILD:18:1: Couldn't build file app/src_kt.jar: Compiling Kotlin to JVM //app:src_kt { kt: 1, java: 1, srcjars: 0 } failed (Exit 1): builder.exe failed: error executing command 
  cd C:/_bazel/iqeeg3eh/execroot/__main__
bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder.exe --flagfile=bazel-out/x64_windows-fastbuild/bin/app/src_kt.jar-0.params.
Exception in thread "main" java.lang.IllegalStateException: runfile manifest C:/_bazel/iqeeg3eh/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder.exe.runfiles/MANIFEST did not contain path mapping for external/com_github_jetbrains_kotlin/lib/kotlin-compiler.jar
	at io.bazel.kotlin.builder.utils.BazelRunFiles.resolveVerified(BazelUtils.kt:72)
	at io.bazel.kotlin.builder.toolchain.KotlinToolchain$Companion.createToolchain(KotlinToolchain.kt:68)
	at io.bazel.kotlin.builder.toolchain.KotlinToolchain.createToolchain(KotlinToolchain.kt)
	at io.bazel.kotlin.builder.KotlinBuilderMain.main(KotlinBuilderMain.java:28)

```

**BUILD**

load("@gmaven_rules//:defs.bzl", "gmaven_artifact")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

PACKAGE = "uk.co.mcneice.bazeltest"
MANIFEST = "src/main/BazelAndroidManifest.xml"

android_binary(
    name = "AndroidBazelExample",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    multidex = "native",
    dex_shards = 10,
    deps = [
        "src"
    ]
)

kt_android_library(
    name = "src",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    srcs = glob(["src/main/java/**"]),
    resource_files = glob(["src/main/res/**"]),
    deps = [
        gmaven_artifact("androidx.appcompat:appcompat:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.constraintlayout:constraintlayout:aar:1.1.2"),

        # The following are transitive dependencies of the above
        gmaven_artifact("androidx.annotation:annotation:1.0.0-beta01"),
        gmaven_artifact("androidx.fragment:fragment:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-common:2.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-viewmodel:aar:2.0.0-beta01"),
        gmaven_artifact("androidx.core:core:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.drawerlayout:drawerlayout:aar:1.0.0-beta01")
    ]
)

**Comment by v5out** [comment]
Did you ever get this working? Thanks!

**Comment by ellenpoe** [comment]
Try a more recent hash for your version. I used this and it worked:

```
rules_kotlin_version = "f7a3b5fd823c2418fc2c2881c00e27e4d63475d5"
```
