### ISSUE TITLE
Bazel 0.23 incompatibility (flag: --incompatible_disallow_data_transition)

### ISSUE THREAD

**Issue by gertvdijk** [bazelbuild/rules_kotlin#172]
Running the latest rules_kotlin with Bazel 0.23rc1 results in the following error:

    ERROR: /path/to/bazel/cache/506e07fbc4424217237e9016567d4898/external/io_bazel_rules_kotlin/kotlin/internal/js/js.bzl:57:17: Traceback (most recent call last):
            File "/path/to/bazel/cache/506e07fbc4424217237e9016567d4898/external/io_bazel_rules_kotlin/kotlin/internal/js/js.bzl", line 50
                    rule(attrs = {"srcs": attr.label_list...")}, <4 more arguments>)
            File "/path/to/bazel/cache/506e07fbc4424217237e9016567d4898/external/io_bazel_rules_kotlin/kotlin/internal/js/js.bzl", line 57, in rule
                    attr.label_list(allow_files = True, default = [], cf...")
    Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
    ERROR: error loading package '': in /path/to/bazel/cache/506e07fbc4424217237e9016567d4898/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl: Extension file 'kotlin/internal/js/js.bzl' has errors
    ERROR: error loading package '': in /path/to/bazel/cache/506e07fbc4424217237e9016567d4898/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl: Extension file 'kotlin/internal/js/js.bzl' has errors

It is mentioned in [the 0.23rc1 release notes](https://releases.bazel.build/0.23.0/rc1/index.html):

> Incompatible flag --incompatible_disallow_data_transition was flipped: cfg = "data" is outdated syntax that was turned into a no-op recently. Support for it was now completely removed.

I believe it's this snippet causing the error:

https://github.com/bazelbuild/rules_kotlin/blob/a632c3a30bb0bd9f5f88fb771489809b9aba602f/kotlin/internal/js/js.bzl#L57-L60

**Comment by gertvdijk** [comment]
It seems that I had spoken too soon. After cleaning the Bazel cache and double checking the version in my WORKSPACE I can't reproduce this any longer. (Perhaps I had an older sha256sum of rules_kotlin that matched my cache and I wasn't actually using the latest version.)
