### ISSUE TITLE
Noob getting error in kt_jvm_test rule script in a project with no tests

### ISSUE THREAD

**Issue by MarkChuCarroll** [bazelbuild/rules_kotlin#182]
I'm just starting to experiment with using bazel to built kotlin. I've created a new project,
with just one source file, named src/main/kotlin/org/goodmath/polytope/storage/storage.kt.
To build it, I put a BUILD file in src/main/kotlin/org/goodmath/polytope/storage/BUILD, containing:

```
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name="storage",
    srcs  = glob(["*.kt"]),
    deps = []
)
```

My WORKSPACE file contains nothing but the kotlin configuration, which I copied from the README.

When I run it, I get the following cascade of errors:

```
DEBUG: Rule 'io_bazel_rules_kotlin' modified arguments {"sha256": "48116981ac03809f0578bfa9ea52c934cb1db118d8aaee15a38495e867321fda"}
ERROR: /private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:218:13: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 205
		dict((_implicit_deps.items() + {"srcs...()))
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 205, in dict
		{"srcs": attr.label_list(default = [], allow_files = _kt_compile_filetypes), "deps": attr.label_list(aspects = [_kt_jvm_plugin_aspect]), "runtime_deps": attr.label_list(default = []), "resources": attr.label_list(default = [], allow_files = True), "resource_strip_prefix": attr.string(default = ""), "resource_jars": attr.label_list(default = []), "data": attr.label_list(allow_files = True, cfg = "data"), "plugins": attr.label_list(default = [], aspects = [_kt_jvm_plugin_aspect]), "module_name": attr.string()}.items()
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 218, in {"srcs": attr.label_list
		attr.label_list(allow_files = True, cfg = "data")
Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
ERROR: /private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:229:30: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 229
		dict((_common_attr.items() + {"jvm_fl...()))
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 229, in dict
		_common_attr
global variable '_common_attr' is referenced before assignment.
ERROR: /private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:269:18: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 268
		rule(attrs = dict((_common_attr.items...())), <3 more arguments>)
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 269, in rule
		dict((_common_attr.items() + {"export...()))
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 269, in dict
		_common_attr
global variable '_common_attr' is referenced before assignment.
ERROR: /private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:298:18: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 297
		rule(attrs = dict((_runnable_common_a...())), <4 more arguments>)
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 298, in rule
		dict((_runnable_common_attr.items() +...()))
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 298, in dict
		_runnable_common_attr
global variable '_runnable_common_attr' is referenced before assignment.
ERROR: /private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:317:18: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 316
		rule(attrs = dict((_runnable_common_a...())), <5 more arguments>)
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 317, in rule
		dict((_runnable_common_attr.items() +...()))
	File "/private/var/tmp/_bazel_markc/2021e78f1a97c6faf84f0332e589e8b0/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 317, in dict
		_runnable_common_attr
global variable '_runnable_common_attr' is referenced before assignment.
ERROR: error loading package '': Extension file 'kotlin/kotlin.bzl' has errors
ERROR: error loading package '': Extension file 'kotlin/kotlin.bzl' has errors
INFO: Elapsed time: 0.086s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by cgruber** [comment]
This is related to the version of bazel you're using.  When bazel changes an API or does something else that renders rules incompatible, it first makes a change to make that API disabled under a flag, and defaults the flag to backwards compatible.  Then the next version, they default the flag to not backwards compatible (but you can explicitly call the flag yourself to preserve yourself). However, the next release of bazel will remove the API/feature and remove the flag, and your ability to be backward compabile.

It's supposed to give rule maintainers the time to fix their rules, and for people using them to upgrad ethe versions of rules they use.  Sadly, in this case, the rules_kotlin are in a bit of a limbo until the team at Google that just took them over can roll out their changes.

the key phrase in the error was here: `Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.'

Your choices are: Use a prior version of Bazel that's compatible, or call bazel with `--incompatible_disallow_data_transition=false`. 

Hopefully the rules will be patched soon.
