### ISSUE TITLE
Can not run Bazel with kotlin rules

### ISSUE THREAD

**Issue by mig35** [bazelbuild/rules_kotlin#189]
I have a sample project with one Java Activity and one Kotlin class. If I remove dependencies on Kotlin class - bazel works fine, but not if I include Kotlin.

My WORKSPACE file is:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(
    name = "androidsdk",
    api_level = 28,
    build_tools_version = "28.0.3"
)

http_archive(
    name = "rules_android",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
)

RULES_JVM_EXTERNAL_TAG = "2.0.1"
RULES_JVM_EXTERNAL_SHA = "55e8d3951647ae3dffde22b4f7f8dee11b3f70f3f89424713debd7076197eaca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "androidx.appcompat:appcompat:1.0.2",
        "androidx.constraintlayout:constraintlayout:1.1.3",
        "com.google.android.material:material:1.0.0",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    fetch_sources = True,
)

rules_kotlin_version = "67f4a6050584730ebae7f8a40435a209f8e0b48e"
http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()
```

After adding last portion with Kotlin rules project is not able to compile:
```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --

ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:122:25: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false.
ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:127:17: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false.
ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:129:20: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false.
ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:208:23: Traceback (most recent call last):
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 205
		dict((_implicit_deps.items() + {"srcs...()))
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 205, in dict
		{"srcs": attr.label_list(default = [], allow_files = _kt_compile_filetypes), "deps": attr.label_list(aspects = [_kt_jvm_plugin_aspect]), "runtime_deps": attr.label_list(default = []), "resources": attr.label_list(default = [], allow_files = True), "resource_strip_prefix": attr.string(default = ""), "resource_jars": attr.label_list(default = []), "data": attr.label_list(allow_files = True, cfg = "data"), "plugins": attr.label_list(default = [], aspects = [_kt_jvm_plugin_aspect]), "module_name": attr.string()}.items()
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 206, in {"srcs": attr.label_list
		attr.label_list(default = [], allow_files = _kt_co...)
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 208, in attr.label_list
		_kt_compile_filetypes
global variable '_kt_compile_filetypes' is referenced before assignment.
ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:229:30: Traceback (most recent call last):
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 229
		dict((_common_attr.items() + {"jvm_fl...()))
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 229, in dict
		_common_attr
global variable '_common_attr' is referenced before assignment.
ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:269:18: Traceback (most recent call last):
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 268
		rule(attrs = dict((_common_attr.items...())), <3 more arguments>)
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 269, in rule
		dict((_common_attr.items() + {"export...()))
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 269, in dict
		_common_attr
global variable '_common_attr' is referenced before assignment.
ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:298:18: Traceback (most recent call last):
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 297
		rule(attrs = dict((_runnable_common_a...())), <4 more arguments>)
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 298, in rule
		dict((_runnable_common_attr.items() +...()))
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 298, in dict
		_runnable_common_attr
global variable '_runnable_common_attr' is referenced before assignment.
ERROR: C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:317:18: Traceback (most recent call last):
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 316
		rule(attrs = dict((_runnable_common_a...())), <5 more arguments>)
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 317, in rule
		dict((_runnable_common_attr.items() +...()))
	File "C:/users/mig35/_bazel_mig35/ofrnxjpe/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl", line 317, in dict
		_runnable_common_attr
global variable '_runnable_common_attr' is referenced before assignment.
ERROR: error loading package '': Extension file 'kotlin/kotlin.bzl' has errors.
Sync failed
```

Has the same error on Windows 10 and MacOS. Bazel version is 0.25.2.

Can you help me? What am I doing wrong?

**Comment by mig35** [comment]
I made this work. May be that will help someone:

WORKSPACE file:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

android_sdk_repository(
    name = "androidsdk",
    api_level = 28,
    build_tools_version = "28.0.3"
)

http_archive(
    name = "rules_android",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
)

RULES_JVM_EXTERNAL_TAG = "2.0.1"
RULES_JVM_EXTERNAL_SHA = "55e8d3951647ae3dffde22b4f7f8dee11b3f70f3f89424713debd7076197eaca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "androidx.appcompat:appcompat:1.0.2",
        "androidx.constraintlayout:constraintlayout:1.1.3",
        "com.google.android.material:material:1.0.0",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    fetch_sources = True,
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_kotlin_version = "f7a3b5fd823c2418fc2c2881c00e27e4d63475d5"
rules_kotlin_compiler_release = {
    "urls": [
        "https://github.com/JetBrains/kotlin/releases/download/v1.2.70/kotlin-compiler-1.2.70.zip",
    ],
    "sha256": "a23a40a3505e78563100b9e6cfd7f535fbf6593b69a5c470800fbafbeccf8434",
}

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/globegitter/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version,
    sha256 = "716127f93bfb09c577712c049b0812640f293362db2714489b78cb231c020a29",
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()
```

BUILD file:
```
load("@rules_jvm_external//:defs.bzl", "artifact")
load("@rules_android//android:rules.bzl", "android_library")

package(default_visibility = ["//visibility:private"])
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")


PACKAGE = "io.scal.bazel"
MANIFEST = "AndroidManifest.xml"

android_library(
    name = "bazel_res",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    resource_files = glob(["res/**"]),
    deps = [
        artifact("androidx.constraintlayout:constraintlayout"),
        artifact("com.google.android.material:material"),
    ],
)

android_library(
    name = "bazel_java",
    srcs = glob(["java/**/*.java"]),
    deps = [
        ":bazel_res",
        ":bazel_kt",
        artifact("androidx.appcompat:appcompat"),
    ]
)

kt_android_library(
    name = "bazel_kt",
    srcs = glob(["java/**/*.kt"]),
    deps = [
        ":bazel_res",
    ]
)

android_binary(
    name = "bazel",
    manifest = MANIFEST,
    custom_package = PACKAGE,
    manifest_values = {
        "minSdkVersion": "21",
        "versionCode" : "2",
        "versionName" : "0.2",
        "targetSdkVersion": "28",
    },
    deps = [
        ":bazel_res",
        ":bazel_java",
        ":bazel_kt",
        artifact("androidx.appcompat:appcompat"),
    ],
)
```
