### ISSUE TITLE
kt_js_import fails for kotlinx atomicfu import

### ISSUE THREAD

**Issue by jasonwyatt** [bazelbuild/rules_kotlin#219]
I'm seeing the following error when trying to set up a `kt_js_import` for AtomicFu:

```
ERROR: /Users/jwf/GitHub/[REDACTED]/BUILD:5:1: Action [REDACTED]/atomicfu-js.js failed (Exit 1) importer failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/kotlin/internal/js/importer --jar external/maven/v1/https/jcenter.bintray.com/org/jetbrains/kotlinx/atomicfu-js/0.13.1/atomicfu-js-0.13.1.jar --out ... (remaining 3 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jwf/c103462cb8cae3463e19adc48a04ad0a/sandbox/darwin-sandbox/87/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_kotlin/kotlin/internal/js/importer.runfiles/io_bazel_rules_kotlin/kotlin/internal/js/importer.py", line 64, in <module>
    _main(parser)
  File "/private/var/tmp/_bazel_jwf/c103462cb8cae3463e19adc48a04ad0a/sandbox/darwin-sandbox/87/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_kotlin/kotlin/internal/js/importer.runfiles/io_bazel_rules_kotlin/kotlin/internal/js/importer.py", line 51, in _main
    _extract_root_entry(args.jar, args.out)
  File "/private/var/tmp/_bazel_jwf/c103462cb8cae3463e19adc48a04ad0a/sandbox/darwin-sandbox/87/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_kotlin/kotlin/internal/js/importer.runfiles/io_bazel_rules_kotlin/kotlin/internal/js/importer.py", line 45, in _extract_root_entry
    raise ex
  File "/private/var/tmp/_bazel_jwf/c103462cb8cae3463e19adc48a04ad0a/sandbox/darwin-sandbox/87/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_kotlin/kotlin/internal/js/importer.runfiles/io_bazel_rules_kotlin/kotlin/internal/js/importer.py", line 38, in _extract_root_entry
    jar.read(basename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1314, in read
    with self.open(name, "r", pwd) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'atomicfu-js.js' in the archive"
```

My `BUILD` file has this:

```python
kt_js_import(
    name = "atomicfu-js",
    jars = [
        "@maven//:org_jetbrains_kotlinx_atomicfu_js"
    ],
    srcjar = "atomicfu-js-0.13.1-sources.jar"
)
```

When in my `WORKSPACE`, I've got:

```python
maven_install(
    artifacts = [
        # other things....
        "org.jetbrains.kotlinx:atomicfu-js:0.13.1",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
```

I think this is because the `.js` file in the jar on maven is named `kotlinx-atomicfu.js` and not `atomicfu-js.js`:

![image](https://user-images.githubusercontent.com/135470/67260739-d4216f00-f451-11e9-9682-ae62ec380cb7.png)

**Comment by cgruber** [comment]
Hmm. Unfortunately, I'm maintaining the legacy branch and I have very little understanding of the JS use-cases involved here, or how it stages its information.  I can try to take a peek at importer.bzl, and see if there's some obvious heuristics we can apply, but this may take some back and forth, and I don't know that I can prioritize it. :/

**Comment by cgruber** [comment]
I'm wondering if the kt_js_import needs a "prefix=" field to let someone specify both the package root, but also the names used for the root javascript file. But I don't know if that's too ham-fisted a solution.

**Comment by jasonwyatt** [comment]
I'm not super familiar with KotlinJS, but if it's a common pattern that compiled KotlinJS libs only have a single javascript file, would it suffice to pick the only file that ends in just `.js`? (e.g. ignoring `.meta.js` and `.js.map` in this example)
