### ISSUE TITLE
--strategy=KotlinCompile=worker not compatible with remote build

### ISSUE THREAD

**Issue by zhuhaow** [bazelbuild/rules_kotlin#337]
I'm using the master branch.

The error message is similar to #325 but the issue only happens when building remotely (https://blog.bazel.build/2018/10/05/remote-build-execution.html)

```
for k8 failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Broken pipe
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
        at com.google.devtools.build.lib.worker.Worker.putRequest(Worker.java:128)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:377)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:199)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:135)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:238)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:126)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:96)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:39)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:327)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:124)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:961)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1109)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1080)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:137)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:80)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:601)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:907)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---
```

The error log suggests the real issue is the jdk is not found for the worker, which should be correctly set (since all java targets build just fine) for remote.

```
/usr/local/google/home/****/.cache/bazel/_bazel_****/031e8c78d570d52b2ec4cd83c73b8d61/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder: line 349: /usr/lib/jvm/11.29.3-ca-jdk11.0.2/reduced/bin/java: No such file or directory
```

Is it possible that the kotlin worker is somewhat started locally?

.bazelrc
```
...
build:remote --host_javabase=@rbe_default//java:jdk
build:remote --javabase=@rbe_default//java:jdk
build:remote --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
build:remote --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
...
```

WORKSPACE
```
...
http_archive(
    name = "bazel_toolchains",
    sha256 = "d0a2219b1d9edbc430413127b9e01502bb35b3e0bdd14b5a53ad1c30ee4fda5e",
    strip_prefix = "bazel-toolchains-3.1.2",
    urls = [
        "https://github.com/bazelbuild/bazel-toolchains/archive/3.1.2.tar.gz",
    ],
)

load("@bazel_toolchains//rules:rbe_repo.bzl", "rbe_autoconfig")

rbe_autoconfig(
    name = "rbe_default",
    java_home = "/usr/lib/jvm/11.29.3-ca-jdk11.0.2/reduced",
)
...
```

**Comment by restingbull** [comment]
The kotlin compilation is a bit non-hermetic when it comes to using the jdk.

That said, few questions:
* Does it work without workers?
* Can you give a bit more of the actual error message?

**Comment by zhuhaow** [comment]
It works fine without the workers, and it works fine when building locally with the workers.

I'm only asking this since the building log would suggest me to add `--strategy=KotlinCompile=worker` when building and adding it won't work for building remotely.

**Comment by zhuhaow** [comment]
All error messages are the `java.io.IOException: Broken pipe` exception and the java not found error (there is only one line in the log file)

**Comment by zhuhaow** [comment]
I think this issue is a not really an issue but wrong HINT message from the rules.

The remote build requires strategy "remote" which of course won't work with worker mode. But the rule won't give hint of adding `build --strategy=KotlinCompile=worker` to bazelrc whenever we are not using worker mode
