### ISSUE TITLE
Android Studio / --kotlin_debug_tags is not optional

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/rules_kotlin#426]
When trying to Bazel sync on Android Studio, I get an exception:

```
ERROR: /home/kernald/dev/monos/javatests/fr/enoent/lighthouse/widgets/BUILD:139:26: Couldn't build file javatests/fr/enoent/lighthouse/widgets/linear_layout_horizontal_absolute_size_test_render_binary_lib.jdeps: Jdeps //javatests/fr/enoent/lighthouse/widgets:linear_layout_horizontal_absolute_size_test_render_binary_lib failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder ... (remaining 1 argument(s) skipped)
--kotlin_debug_tags is not optionalDec 09, 2020 07:17:24 AM io.bazel.kotlin.builder.tasks.PersistentWorker run
SEVERE: ERROR: Worker threw uncaught exception
java.lang.IllegalArgumentException: --kotlin_debug_tags is not optional
	at io.bazel.kotlin.builder.utils.ArgMap.mandatory(ArgMap.kt:63)
	at io.bazel.kotlin.builder.utils.ArgMap.mandatory(ArgMap.kt:76)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.buildTaskInfo(KotlinBuilder.kt:161)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.buildContext(KotlinBuilder.kt:153)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.apply(KotlinBuilder.kt:123)
	at io.bazel.kotlin.builder.tasks.PersistentWorker.run(BazelWorker.kt:168)
	at io.bazel.kotlin.builder.tasks.BazelWorker.apply(BazelWorker.kt:74)
	at io.bazel.kotlin.builder.KotlinBuilderMain.main(KotlinBuilderMain.java:28)
```

This happens for pretty much every single `kt_*` target I have.

Bazel 3.7.1, rules_kotlin v1.5.0-alpha-1.

**Comment by ryanpbrewster** [comment]
I am also running into this. I have bisected it down to https://github.com/bazelbuild/rules_kotlin/pull/379

commit 95b642f10fb9c73312edd59bcf6ba6250ef8a2cb works
commit 2be75c0151b05a4ac1b17ee509e9d7737c8ccc67 fails

**Comment by jongerrish** [comment]
Hey Ryan, this fixed at head now since https://github.com/bazelbuild/rules_kotlin/commit/7e57f143a4a85198b162cac4098e922ebca3774b

@cgruber when are you planning to push an `alpha-2` ?

**Comment by restingbull** [comment]
`alpha-2` is released. @ryanpbrewster, please verify this issue.

**Comment by ryanpbrewster** [comment]
Verified, the command fails on `1.5.0-alpha-1` and succeeds now on `1.5.0-alpha-2`. Thanks!
