### ISSUE TITLE
Syncing with IntelliJ after using 1.5.0-alpha throws an exception

### ISSUE THREAD

**Issue by pratik-brex** [bazelbuild/rules_kotlin#427]
Upgraded to the newest release and after syncing in IntelliJ it fails with this:

Bazel command IntelliJ invokes to resync:

```
Command: /usr/local/bin/bazel build --tool_tag=ijwb:IDEA:community --keep_going --build_event_binary_file=/var/folders/d_/t4d0l38s2j1brhp3lnkm78380000gn/T/intellij-bep-f7a22d1b-a731-43ec-befc-50789d48916a --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/ptandel/Library/Application Support/JetBrains/IdeaIC2020.1/plugins/ijwb/aspect" --output_groups=intellij-info-generic,intellij-info-java-direct-deps,intellij-info-kt-direct-deps,intellij-resolve-java-direct-deps,intellij-resolve-kt-direct-deps -- <list of targets>
```

```
ERROR: /private/var/tmp/_bazel_ptandel/e07d0e79a4305759b5540e9a9be65f3c/external/com_github_grpc_grpc_kotlin/stub/src/main/java/io/grpc/kotlin/BUILD.bazel:9:15: Couldn't build file external/com_github_grpc_grpc_kotlin/stub/src/main/java/io/grpc/kotlin/stub.jdeps: Jdeps @com_github_grpc_grpc_kotlin//stub/src/main/java/io/grpc/kotlin:stub failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder ... (remaining 1 argument(s) skipped)
--kotlin_debug_tags is not optionalDec 09, 2020 4:15:34 PM io.bazel.kotlin.builder.tasks.PersistentWorker run
SEVERE: ERROR: Worker threw uncaught exception
java.lang.IllegalArgumentException: --kotlin_debug_tags is not optional
	at io.bazel.kotlin.builder.utils.ArgMap.mandatory(ArgMap.kt:63)
	at io.bazel.kotlin.builder.utils.ArgMap.mandatory(ArgMap.kt:76)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.buildTaskInfo(KotlinBuilder.kt:161)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.buildContext(KotlinBuilder.kt:153)
	at io.bazel.kotlin.builder.tasks.KotlinBuilder.apply(KotlinBuilder.kt:123)
	at io.bazel.kotlin.builder.tasks.PersistentWorker.run(BazelWorker.kt:168)
	at io.bazel.kotlin.builder.tasks.BazelWorker.apply(BazelWorker.kt:74)
	at io.bazel.kotlin.builder.KotlinBuilderMain.main(KotlinBuilderMain.java:28)
```

**Comment by pratik-brex** [comment]
Duplicate of https://github.com/bazelbuild/rules_kotlin/issues/426
