### ISSUE TITLE
Parameter 'output_jar' is deprecated and will be removed soon

### ISSUE THREAD

**Issue by Nikolas-LFDesigns** [bazelbuild/rules_kotlin#447]
I have the following error on rules_kotlin 1.5.0 alpha 1 and higher:
```in kt_jvm_library rule [this is my rule for library]: 
Traceback (most recent call last):
	File "[...]/e810e7b62577a3b59b8845a708b42f0a/external/io_bazel_rules_kotlin/kotlin/internal/jvm/impl.bzl", line 165, column 36, in kt_jvm_library_impl
		_kt_jvm_produce_jar_actions(ctx, "kt_jvm_library") if ctx.attr.srcs else export_only_providers(
	File "[...]/e810e7b62577a3b59b8845a708b42f0a/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 592, column 42, in kt_jvm_produce_jar_actions
		source_jar = java_common.pack_sources(
Error in pack_sources: in call to pack_sources(), parameter 'output_jar' is deprecated and will be removed soon. It may be temporarily re-enabled by setting --incompatible_java_common_parameters=false```
Environment:
Bazel: 3.7.0 linux
OS: Ubuntu 20.04

Is it possible that the project is really using deprecated API, or is it something on my side that I didn't count in when building?

**Comment by restingbull** [comment]
Probably deprecated. I'll take a look.

**Comment by Nikolas-LFDesigns** [comment]
@restingbull any updates here?
