### ISSUE TITLE
alpha-3 running into manifest issues

### ISSUE THREAD

**Issue by jeffzoch** [bazelbuild/rules_kotlin#456]
I recently switched back to alpha-3 after using a private fork of an old version from 2 months back and am encountering issues building an executable jar using the springboot rules:

```
INFO: From Executing genrule //projects/services/dataprotection/winterfell-syncmaster:projects/services/service_genjar:
cp: /private/var/tmp/_bazel_j.zoch/8bdf7aad5539a314ee98a49e42674806/sandbox/darwin-sandbox/777/execroot/__main__/external/remote_java_tools_darwin/java_tools/src/tools/singlejar/singlejar_local0: No such file or directory
java.io.IOException: invalid manifest format
	at java.base/java.util.jar.Manifest.read(Manifest.java:257)
	at java.base/java.util.jar.Manifest.<init>(Manifest.java:80)
	at java.base/java.util.jar.Manifest.<init>(Manifest.java:72)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:268)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)
java.io.FileNotFoundException: /private/var/tmp/_bazel_j.zoch/8bdf7aad5539a314ee98a49e42674806/sandbox/darwin-sandbox/777/execroot/__main__/bazel-out/darwin-fastbuild/bin/projects/services/service.jar.raw (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:360)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)
java.io.FileNotFoundException: /private/var/tmp/_bazel_j.zoch/8bdf7aad5539a314ee98a49e42674806/sandbox/darwin-sandbox/777/execroot/__main__/bazel-out/darwin-fastbuild/bin/projects/services/service.jar.raw (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:360)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)
singlejar_local: ./src/tools/singlejar/mapped_file_posix.inc:42: open /private/var/tmp/_bazel_j.zoch/8bdf7aad5539a314ee98a49e42674806/sandbox/darwin-sandbox/777/execroot/__main__/bazel-out/darwin-fastbuild/bin/projects/services/service.jar.raw:: No such file or directory
singlejar_local: src/tools/singlejar/input_jar.cc:23: Cannot open input jar /private/var/tmp/_bazel_j.zoch/8bdf7aad5539a314ee98a49e42674806/sandbox/darwin-sandbox/777/execroot/__main__/bazel-out/darwin-fastbuild/bin/projects/services/service.jar.raw: No such file or directory
```

Using  the following toolchain:
```
kt_kotlinc_options(
    name = "kotlinc_options",
    x_inline_classes = True,
    x_allow_result_return_type = True,
)

kt_javac_options(
    name = "default_javac_options",
)
define_kt_toolchain(
    name = "kotlin_toolchain",
    api_version = "1.4"
    jvm_target = "1.8",  # "1.6", "1.8", "9", "10", "11", or "12",
    language_version = "1.4"
    javac_options = ":default_javac_options",
    kotlinc_options = ":kotlinc_options",
)

```

**Comment by jeffzoch** [comment]
Seems to be a spring boot rule issue - https://github.com/salesforce/bazel-springboot-rule/issues/81
