### ISSUE TITLE
StackOverflowError during jdeps generation

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/rules_kotlin#485]
Encountered this one while doing some testing with the latest master. Seems to be the result of generic class types that reference themself. Example from Junit:

```java
public abstract class AbstractObjectAssert<SELF extends AbstractObjectAssert<SELF, ACTUAL>, ACTUAL>
    extends AbstractAssert<SELF, ACTUAL> {
...
```

```console
exception: java.lang.StackOverflowError
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.isTypeConstructorForGivenClass(KotlinBuiltIns.java:724)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.isConstructedFromGivenClass(KotlinBuiltIns.java:716)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.isNothingOrNullableNothing(KotlinBuiltIns.java:841)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.isNothing(KotlinBuiltIns.java:831)
        at org.jetbrains.kotlin.types.TypeSubstitutor.unsafeSubstitute(TypeSubstitutor.java:198)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substituteTypeArguments(TypeSubstitutor.java:329)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substituteCompoundType(TypeSubstitutor.java:308)
        at org.jetbrains.kotlin.types.TypeSubstitutor.unsafeSubstitute(TypeSubstitutor.java:245)
        at org.jetbrains.kotlin.types.TypeSubstitutor.unsafeSubstitute(TypeSubstitutor.java:173)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substituteWithoutApproximation(TypeSubstitutor.java:126)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:111)
        at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:104)
        at org.jetbrains.kotlin.types.StarProjectionImplKt.starProjectionType(StarProjectionImpl.kt:55)
        at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:35)
        at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:26)
        at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
        at org.jetbrains.kotlin.types.StarProjectionImpl.get_type(StarProjectionImpl.kt)
        at org.jetbrains.kotlin.types.StarProjectionImpl.getType(StarProjectionImpl.kt:38)
        at org.jetbrains.kotlin.types.TypeProjectionBase.hashCode(TypeProjectionBase.java:49)
        at java.base/java.util.ArrayList.hashCodeRange(ArrayList.java:627)
        at java.base/java.util.ArrayList.hashCode(ArrayList.java:614)
        at org.jetbrains.kotlin.types.KotlinType.computeHashCode(KotlinType.kt:96)
        at org.jetbrains.kotlin.types.KotlinType.hashCode(KotlinType.kt:106)
        at java.base/java.util.HashMap.hash(HashMap.java:339)
        at java.base/java.util.HashMap.put(HashMap.java:607)
        at java.base/java.util.HashSet.add(HashSet.java:220)
        at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
        at org.jetbrains.kotlin.types.TypeUtils.collectAllSupertypes(TypeUtils.java:272)
        at org.jetbrains.kotlin.types.TypeUtils.getAllSupertypes(TypeUtils.java:284)
        at org.jetbrains.kotlin.types.typeUtil.TypeUtilsKt.supertypes(TypeUtils.kt:53)
        at io.bazel.kotlin.plugin.jdeps.JdepsGenExtension$ClasspathCollectingChecker.collectTypeArguments(JdepsGenExtension.kt:230)
        at io.bazel.kotlin.plugin.jdeps.JdepsGenExtension$ClasspathCollectingChecker.collectTypeArguments(JdepsGenExtension.kt:231)
        at io.bazel.kotlin.plugin.jdeps.JdepsGenExtension$ClasspathCollectingChecker.collectTypeArguments(JdepsGenExtension.kt:231)
        at io.bazel.kotlin.plugin.jdeps.JdepsGenExtension$ClasspathCollectingChecker.collectTypeArguments(JdepsGenExtension.kt:231)
        at io.bazel.kotlin.plugin.jdeps.JdepsGenExtension$ClasspathCollectingChecker.collectTypeArguments(JdepsGenExtension.kt:231)
....
```

**Comment by Bencodes** [comment]
@jongerrish

**Comment by jongerrish** [comment]
Thanks Ben, I'll take a look this afternoon!

**Comment by Bencodes** [comment]
I put up a fix for this already https://github.com/bazelbuild/rules_kotlin/pull/486
