### ISSUE TITLE
Create an example executing spek via junit4 runner or await support of a Jupiter runner

### ISSUE THREAD

**Issue by pardom** [bazelbuild/rules_kotlin#50]
I'm trying to get Kotlin testing working on a Java project. I've tried using the `rules_kotlin` docs along with the `java_test` docs example here: https://docs.bazel.build/versions/master/be/java.html#java_test 

and this example:
https://github.com/bazelbuild/bazel/blob/master/examples/java-native/src/test/java/com/example/myproject/BUILD

Below are the relevant build files:

https://github.com/ReduxJava/reduxjava/blob/bazel/WORKSPACE
https://github.com/ReduxJava/reduxjava/blob/bazel/reduxjava-api/BUILD
https://github.com/ReduxJava/reduxjava/blob/bazel/reduxjava/BUILD

And the resulting output:

```
$ bazel test //reduxjava:store_impl
ERROR: /Source/ReduxJava/reduxjava/reduxjava/BUILD:39:1: in kt_jvm_test rule //reduxjava:store_impl:


The following files have no generating action:
reduxjava/store_impl-sources.jar
ERROR: Analysis of target '//reduxjava:store_impl' failed; build aborted: Analysis of target '//reduxjava:store_impl' failed; build aborted
INFO: Elapsed time: 0.113s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

I should mention that this is using [Spek](http://spekframework.org/) which requires a [custom test runner](http://spekframework.org/docs/latest/#setting-up-legacy) for JUnit 4. I've also tried other `kt_jvm_test` configurations with different resultant errors, however I think those were improperly configured anyway.

* Could we get some better documentation and examples for Kotlin rules?
* Should they work the same way as the Java Rules, i.e. can I use those as reference?
* Is there anything wrong with my build files which would result in the error output above?

**Comment by pardonut** [comment]
If I use the following configuration:

```py
kt_jvm_test(
    name = "store_impl",
    srcs = glob(["src/test/kotlin/redux/**/*.kt"]),
    deps = [
        "//reduxjava-api:reduxjava-api",
        ":reduxjava",
        "@com_google_truth_truth//jar",
        "@junit_junit//jar",
        ":org_jetbrains_spek_spek_api",
        "@org_jetbrains_spek_spek_junit_platform_engine//jar",
        "@org_junit_platform_junit_platform_runner//jar",
        "@org_mockito_mockito_core//jar",
    ],
    test_class = "redux.StoreImplTest",
)
```

I get the following output:

```
$ bazel test //reduxjava:store_impl
INFO: Analysed target //reduxjava:store_impl (1 packages loaded).
INFO: Found 1 test target...
INFO: From Compiling 5 Kotlin source files to reduxjava/store_impl.jar:
HINT: KotlinCompile will compile faster if you run: echo "build --strategy=KotlinCompile=worker" >>~/.bazelrc
FAIL: //reduxjava:store_impl (see /private/var/tmp/_bazel_pardom/b550c483f6ee384067cc498ad51a3a81/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/reduxjava/store_impl/test.log)
Target //reduxjava:store_impl up-to-date:
  bazel-bin/reduxjava/store_impl.jar
INFO: Elapsed time: 6.661s, Critical Path: 6.51s
INFO: Build completed, 1 test FAILED, 4 total actions
//reduxjava:store_impl                                                   FAILED in 0.3s
  /private/var/tmp/_bazel_pardom/b550c483f6ee384067cc498ad51a3a81/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/reduxjava/store_impl/test.log

Executed 1 out of 1 test: 1 fails locally.
```

With a test log of:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
JUnit4 Test Runner
.E
Time: 0.005
There was 1 failure:
1) initializationError(redux.StoreImplTest)
java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory
	at org.junit.platform.runner.JUnitPlatform.<init>(JUnitPlatform.java:113)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at com.google.testing.junit.runner.internal.junit4.MemoizingRequest.createRunner(MemoizingRequest.java:48)
	at com.google.testing.junit.runner.internal.junit4.MemoizingRequest.getRunner(MemoizingRequest.java:34)
	at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:51)
	at com.google.testing.junit.runner.junit4.JUnit4TestModelBuilder.get(JUnit4TestModelBuilder.java:30)
	at com.google.testing.junit.runner.util.MemoizingSupplier.get(MemoizingSupplier.java:42)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:92)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.core.LauncherFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2018-04-15 15:27:51 --
```

**Comment by hsyed** [comment]
The default Bazel test runner runner and it's integration to the intellij plugin framework revolve around Junit4. 

I am very interested in adding proper Spek support, however until the bazel Intellij plugin can support junit5 a bit better I won't be able to look into it . 

However you should be able to write a macro for launching your tests. I recommend compiling the Kotlin sources with `kt_jvm_library` and experimenting with a macro using `java_test` and `java_binary`. If memory serves one ways to wrap the junit5 console launcher.

If you do get a macro working I feel it wouldn't belong in `kotlin_rules` but please post your findings. In the medium term Jupiter runner support should hit Bazel core.

**Comment by pardom** [comment]
I'm using JUnit 4 in this project as JUnit 5 doesn't have Android Studio support. There are docs here: http://spekframework.org/docs/latest/#setting-up-legacy

Is it possible to apply this setup with the existing rules?
