### ISSUE TITLE
Starlark error when updating to stardoc 0.5.0

### ISSUE THREAD

**Issue by kormide** [bazelbuild/rules_kotlin#667]
I was attempting to update the stardocs version to `0.5.0` and the stardoc compiler complains about a starlark error. I'm not familiar enough with this code to fix it myself.

This issue is on [this line](https://github.com/bazelbuild/rules_kotlin/blob/master/src/main/starlark/rkt_1_4/jvm/opts.bzl#L34) where a `provider` is being used for the dict key.

Stacktrace:

```
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: Starlark evaluation error
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:428)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:402)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:402)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:260)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:163)
Caused by: Traceback (most recent call last):
	File "./external/rkt_1_4/jvm/opts.bzl", line 34, column 24, in <toplevel>
		derive.info: derive.repeated_values_for("-Xlint:"),
Error: unhashable type: 'Provider'
	at net.starlark.java.eval.Starlark.errorf(Starlark.java:663)
	at net.starlark.java.eval.StarlarkValue.checkHashable(StarlarkValue.java:99)
	at net.starlark.java.eval.Starlark.checkHashable(Starlark.java:152)
	at net.starlark.java.eval.Dict.putEntry(Dict.java:489)
	at net.starlark.java.eval.Eval.evalDict(Eval.java:558)
	at net.starlark.java.eval.Eval.eval(Eval.java:486)
	at net.starlark.java.eval.Eval.evalCall(Eval.java:632)
	at net.starlark.java.eval.Eval.eval(Eval.java:490)
	at net.starlark.java.eval.Eval.evalDict(Eval.java:555)
	at net.starlark.java.eval.Eval.eval(Eval.java:486)
	at net.starlark.java.eval.Eval.execAssignment(Eval.java:109)
	at net.starlark.java.eval.Eval.exec(Eval.java:269)
	at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
	at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
	at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:191)
	at net.starlark.java.eval.Starlark.fastcall(Starlark.java:617)
	at net.starlark.java.eval.Starlark.execFileProgram(Starlark.java:892)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:425)
```

Here is a patch to update stardocs and reproduce the error.
```
diff --git a/src/main/starlark/core/repositories/download.bzl b/src/main/starlark/core/repositories/download.bzl
index 331e7c1..47a9946 100644
--- a/src/main/starlark/core/repositories/download.bzl
+++ b/src/main/starlark/core/repositories/download.bzl
@@ -84,8 +84,10 @@ def kt_download_local_dev_dependencies():
         http_archive,
         name = "io_bazel_stardoc",
         sha256 = versions.IO_BAZEL_STARDOC_SHA,
-        strip_prefix = "stardoc-%s" % versions.IO_BAZEL_STARDOC_VERSION,
-        url = "https://github.com/bazelbuild/stardoc/archive/%s.tar.gz" % versions.IO_BAZEL_STARDOC_VERSION,
+        urls = [
+            "https://github.com/bazelbuild/stardoc/releases/download/%s/stardoc-%s.tar.gz" % (versions.IO_BAZEL_STARDOC_VERSION, versions.IO_BAZEL_STARDOC_VERSION),
+            "https://mirror.bazel.build/github.com/bazelbuild/stardoc/releases/download/%s/stardoc-%s.tar.gz" % (versions.IO_BAZEL_STARDOC_VERSION, versions.IO_BAZEL_STARDOC_VERSION),
+        ]
     )
 
     rules_stardoc_repository(
diff --git a/src/main/starlark/core/repositories/versions.bzl b/src/main/starlark/core/repositories/versions.bzl
index 7d3a55a..d37660b 100644
--- a/src/main/starlark/core/repositories/versions.bzl
+++ b/src/main/starlark/core/repositories/versions.bzl
@@ -22,8 +22,8 @@ versions = struct(
     RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca",
     RULES_PROTO_GIT_COMMIT = "f6b8d89b90a7956f6782a4a3609b2f0eee3ce965",
     RULES_PROTO_SHA = "4d421d51f9ecfe9bf96ab23b55c6f2b809cbaf0eea24952683e397decfbd0dd0",
-    IO_BAZEL_STARDOC_VERSION = "0.4.0",
-    IO_BAZEL_STARDOC_SHA = "6d07d18c15abb0f6d393adbd6075cd661a2219faab56a9517741f0fc755f6f3c",
+    IO_BAZEL_STARDOC_VERSION = "0.5.0",
+    IO_BAZEL_STARDOC_SHA = "c9794dcc8026a30ff67cf7cf91ebe245ca294b20b071845d12c192afe243ad72",
     BAZEL_JAVA_LAUNCHER_VERSION = "5.0.0-pre.20210510.2",
     KOTLIN_CURRENT_COMPILER_RELEASE = version(
         version = "1.5.32",
```

Run
```bazel build //kotlin:stardoc```

**Comment by restingbull** [comment]
Seems like a bug in Stardoc.

**Comment by restingbull** [comment]
Next release of Stardoc will fix this.
