### ISSUE TITLE
1.6.0-RC-1/2  - JDeps Merge Failure

### ISSUE THREAD

**Issue by rob-pomelo** [bazelbuild/rules_kotlin#761]
Tried 1.6.0-RC-2 (coming from 1.5), seeing the following jdeps failure on binary and test targets. 

`SEVERE: ERROR: unexpected exception
java.lang.IllegalArgumentException: --inputs is not optional
	at io.bazel.kotlin.builder.utils.ArgMap.mandatory(ArgMap.kt:63)
	at io.bazel.kotlin.builder.utils.ArgMap.mandatory(ArgMap.kt:76)
	at io.bazel.kotlin.builder.tasks.jvm.JdepsMerger.execute(JdepsMerger.kt:130)
	at io.bazel.kotlin.builder.tasks.MergeJdeps.invoke(MergeJdeps.kt:28)
	at io.bazel.worker.PersistentWorker$workTo$1.invoke(PersistentWorker.kt:97)
	at io.bazel.worker.PersistentWorker$workTo$1.invoke(PersistentWorker.kt:97)
	at io.bazel.worker.WorkerContext$TaskContext.resultOf(WorkerContext.kt:128)
	at io.bazel.worker.WorkerContext.doTask(WorkerContext.kt:156)
	at io.bazel.worker.PersistentWorker$start$1$1$producer$1$1.invoke$lambda-0(PersistentWorker.kt:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`
	
If I had to guess based on the changelogs, it seems this may be a side effect of https://github.com/bazelbuild/rules_kotlin/pull/726 which is resulting in [this](https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/jvm/compile.bzl#L247) being empty, but it is a mandatory input [here](https://github.com/bazelbuild/rules_kotlin/blob/master/src/main/kotlin/io/bazel/kotlin/builder/tasks/jvm/JdepsMerger.kt#L130). If the solution is as simple as checking for jdeps being empty in the `compile.bzl` and skipping the merge call, happy to send a PR, but not sure the implications.

**Comment by rob-pomelo** [comment]
Narrowed this down a bit, the failure arrises when a `kt_jvm_binary` or `kt_jvm_test` target do not have any `srcs` or `deps`. Having trouble nailing down where the regression came from, ruled out #726.

Our codebase pattern is to have a bazel helper rule for tests to build a single kt_jvm_library for all tests in a package and then create a separate test target for each test class that has the meta library as a runtime dep. Similar for `kt_jvm_binary`, we have a `kt_jvm_library` target that the `kt_jvm_binary` target relies on as a runtime dep.

**Comment by Bencodes** [comment]
Thanks for the report! I'd be surprised if https://github.com/bazelbuild/rules_kotlin/pull/726 caused this as it doesn't actually change how jdeps are processed.

Do you have a simple repro example that we can play around with?

**Comment by rob-pomelo** [comment]
Thanks for all the work you all do to maintain!

Created bare minimum repro example for both `kt_jvm_binary` and `kt_jvm_test` in https://github.com/rob-pomelo/bzl-kt-jdeps-repro/tree/main/examples.

And agreed re #726, the example also fails on 1.6.0-RC-1, so that is ruled out.

Let me know if any issues with the repo!

**Comment by Bencodes** [comment]
@rob-pomelo We follow a similar pattern for our java binary targets, the primary difference being that we just use `java_binary` directly instead of `kt_jvm_binary`. Might be why we've never hit this case internally.

**Comment by rob-pomelo** [comment]
Yep for the short term migrated to `java_binary/image` + `java_test`

**Comment by Bencodes** [comment]
@rob-pomelo this should fix the underlying issue https://github.com/bazelbuild/rules_kotlin/pull/763

**Comment by rob-pomelo** [comment]
thank you!
