### ISSUE TITLE
JDK 9: IllegalArgumentException: No enum constant com.sun.tools.javac.main.Option.BOOT_CLASS_PATH

### ISSUE THREAD

**Issue by cushon** [bazelbuild/rules_kotlin#81]
Bazel at head uses JDK 9 as the default host_javabase, and `rules_kotlin` does not appear to be compatible with JDK 9.

```
bazel test //:all_tests
...
ERROR: /usr/local/google/home/cushon/src/rules_kotlin/examples/dagger/BUILD:39:1: Compiling 8 Kotlin source files to examples/dagger/coffee_lib.jar failed (Exit 2)
exception: java.lang.IllegalArgumentException: No enum constant com.sun.tools.javac.main.Option.BOOT_CLASS_PATH
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.sun.tools.javac.main.Option.valueOf(Option.java:67)
	at org.jetbrains.kotlin.kapt3.base.util.Java9UtilsKt.putJavacOption(java9Utils.kt:30)
	at org.jetbrains.kotlin.kapt3.base.KaptContext.<init>(KaptContext.kt:75)
	at org.jetbrains.kotlin.kapt3.KaptContextForStubGeneration.<init>(KaptContextForStubGeneration.kt:43)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.compileStubs(Kapt3Extension.kt:253)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.generateStubs(Kapt3Extension.kt:204)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:151)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:93)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:116)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:85)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:370)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:61)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:361)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyzeAndGenerate(KotlinToJVMBytecodeCompiler.kt:343)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileBunchOfSources(KotlinToJVMBytecodeCompiler.kt:242)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:200)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:95)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
	at io.bazel.kotlin.compiler.BazelK2JVMCompiler.exec(BazelK2JVMCompiler.kt:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.bazel.kotlin.builder.KotlinToolchain$TCModule$kotlincInvoker$1.compile(KotlinToolchain.kt:146)
	at io.bazel.kotlin.builder.mode.jvm.actions.DefaultKotlinCompiler.invokeCompilePhase(KotlinCompiler.kt:92)
	at io.bazel.kotlin.builder.mode.jvm.actions.DefaultKotlinCompiler.runAnnotationProcessor(KotlinCompiler.kt:51)
	at io.bazel.kotlin.builder.mode.jvm.DefaultKotlinJvmCompilationExecutor.runAnnotationProcessors(KotlinJvmCompilationExecutor.kt:69)
	at io.bazel.kotlin.builder.mode.jvm.DefaultKotlinJvmCompilationExecutor.compile(KotlinJvmCompilationExecutor.kt:54)
	at io.bazel.kotlin.builder.KotlinBuilder.doExecute(KotlinBuilder.kt:49)
	at io.bazel.kotlin.builder.KotlinBuilder.execute(KotlinBuilder.kt:36)
	at io.bazel.kotlin.builder.KotlinBuilder.execute(KotlinBuilder.kt:43)
	at io.bazel.kotlin.builder.KotlinBuilder.execute(KotlinBuilder.kt:39)
	at io.bazel.kotlin.builder.KotlinBuilder.apply(KotlinBuilder.kt:102)
	at io.bazel.kotlin.builder.BazelWorker.runAsPersistentWorker(BazelWorker.kt:105)
	at io.bazel.kotlin.builder.BazelWorker.apply(BazelWorker.kt:84)
	at io.bazel.kotlin.builder.KotlinBuilder$Companion.main(KotlinBuilder.kt:109)
	at io.bazel.kotlin.builder.KotlinBuilder.main(KotlinBuilder.kt)

```

**Comment by hsyed** [comment]
Thanks, I'll start looking into it. I have built bazel form head but haven't actually installed or used it. Any tips would be welcome. Are there nightlies available ?

**Comment by hsyed** [comment]
aah looks simple enough. https://docs.bazel.build/versions/master/install-compile-source.html

**Comment by cushon** [comment]
Yep, it should be as simple as getting the prerequisites and doing a `bazel build //src:bazel`, but let me know if you run into any issues with that part.

**Comment by cushon** [comment]
bazelbuild/rules_kotlin#82
