### ISSUE TITLE
`_run_kt_java_builder_actions` references unassigned `java_info` variable

### ISSUE THREAD

**Issue by barm** [bazelbuild/rules_kotlin#877]
Found this issue while attempting to upgrade from 1.5 to 1.6. If there are annotation processors, we try to access `java_info` which is not assigned: 

```starlark
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_brian/543db2c15cef85941ff9c139e2f8f864/external/io_bazel_rules_kotlin/kotlin/internal/jvm/impl.bzl", line 259, column 44, in kt_jvm_junit_test_impl
		providers = _kt_jvm_produce_jar_actions(ctx, "kt_jvm_test")
	File "/private/var/tmp/_bazel_brian/543db2c15cef85941ff9c139e2f8f864/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 491, column 50, in kt_jvm_produce_jar_actions
		outputs_struct = _run_kt_java_builder_actions(
	File "/private/var/tmp/_bazel_brian/543db2c15cef85941ff9c139e2f8f864/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 746, column 56, in _run_kt_java_builder_actions
		ap_class_jar = [jars.class_jar for jars in java_info.outputs.jars][0],
Error: local variable 'java_info' is referenced before assignment.
```

**Comment by barm** [comment]
Just wanted to add a note: I haven't created a minimal project reproducing this yet but I did read the code and I can't find an assignment before it's used. If you need a minimal reproducing project I can look into that as well.
