### ISSUE TITLE
OutOfMemoryError when building with Kotlin 1.8 rc1 rules 

### ISSUE THREAD

**Issue by jbarr21** [bazelbuild/rules_kotlin#925]
kt rules: `1.8rc1` (minor fork)
bazel: `6.0.0` (minor fork)
actions built: `-70k` (android, java, & kt (including mixing kt+java in same target)
log
<summary>java.lang.OutOfMemoryError: Compressed class space (expand for full log)</summary>
<details>
<pre>
```
ERROR: <PATH_REDACTED>/BUILD.bazel:3:24: Building <PATH_REDACTED>/src_release_kt-java.jar (80 source files) and running annotation processors (ExperimentEnumProcessor, AutoAnnotationProcessor, AutoBuilderProcessor, AutoOneOfProcessor, AutoValueBuilderProcessor, AutoValueProcessor, MemoizedValidator, ToPrettyStringValidator, ComponentProcessor, Processor, RaveProcessor, ParameterTrackingProcessor) failed: (Exit 1): java failed: error executing command (from target //<PATH_REDACTED>:src_release_kt) external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 16 arguments skipped)
--
  | java.lang.RuntimeException: java.lang.OutOfMemoryError: Compressed class space
  | at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163)
  | at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  | at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:137)
  | at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileSources(SimpleJavaLibraryBuilder.java:49)
  | at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:110)
  | at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:118)
  | at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:105)
  | at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:85)
  | at com.google.devtools.build.lib.worker.WorkRequestHandler$WorkRequestHandlerBuilder.lambda$new$0(WorkRequestHandler.java:264)
  | at com.google.devtools.build.lib.worker.WorkRequestHandler$WorkRequestCallback.apply(WorkRequestHandler.java:230)
  | at com.google.devtools.build.lib.worker.WorkRequestHandler.respondToRequest(WorkRequestHandler.java:424)
  | at com.google.devtools.build.lib.worker.WorkRequestH
```
</pre>
</details>

I just upgraded our monorepo to 1.8 rc1 rules and am seeing `java.lang.OutOfMemoryError: Compressed class space`. Using `jcmd <PID> VM.metaspace | grep "Class space"` for the JavaBuilder process (likely from using mixed sources) returned by `jcmd -l | grep "JavaBuilder"`...

on v1.7.0-RC-1 kt rules, class space for the JavaBuilder process over the 30-min build:
```
      Class space:        1.00 GB reserved,       4.12 MB ( <1%) committed
      Class space:        1.00 GB reserved,       4.12 MB ( <1%) committed
      Class space:        1.00 GB reserved,       9.38 MB ( <1%) committed
      Class space:        1.00 GB reserved,       9.38 MB ( <1%) committed
      Class space:        1.00 GB reserved,       9.38 MB ( <1%) committed
      Class space:        1.00 GB reserved,       9.38 MB ( <1%) committed
      Class space:        1.00 GB reserved,      15.70 MB (  2%) committed
      Class space:        1.00 GB reserved,      15.70 MB (  2%) committed
      Class space:        1.00 GB reserved,      15.70 MB (  2%) committed
      Class space:        1.00 GB reserved,      16.32 MB (  2%) committed
      Class space:        1.00 GB reserved,      20.89 MB (  2%) committed
      Class space:        1.00 GB reserved,      23.77 MB (  2%) committed
      Class space:        1.00 GB reserved,      34.22 MB (  3%) committed
      Class space:        1.00 GB reserved,      34.22 MB (  3%) committed
      Class space:        1.00 GB reserved,      34.22 MB (  3%) committed
      Class space:        1.00 GB reserved,      38.59 MB (  4%) committed
      Class space:        1.00 GB reserved,      40.34 MB (  4%) committed
      Class space:        1.00 GB reserved,      47.09 MB (  5%) committed
      Class space:        1.00 GB reserved,      51.59 MB (  5%) committed
      Class space:        1.00 GB reserved,      51.59 MB (  5%) committed
      Class space:        1.00 GB reserved,      51.59 MB (  5%) committed
      Class space:        1.00 GB reserved,      53.22 MB (  5%) committed
      Class space:        1.00 GB reserved,      53.22 MB (  5%) committed
      Class space:        1.00 GB reserved,      53.22 MB (  5%) committed
      Class space:        1.00 GB reserved,      53.22 MB (  5%) committed
      Class space:        1.00 GB reserved,      53.22 MB (  5%) committed
      Class space:        1.00 GB reserved,      53.22 MB (  5%) committed
```

on 1.8rc1 kt rules, class space for the JavaBuilder process over the 25 min (usually 30min) build:
```
      Class space:        1.00 GB reserved,       4.12 MB ( <1%) committed
      Class space:        1.00 GB reserved,       6.00 MB ( <1%) committed
      Class space:        1.00 GB reserved,      14.12 MB (  1%) committed
      Class space:        1.00 GB reserved,      14.12 MB (  1%) committed
      Class space:        1.00 GB reserved,      14.12 MB (  1%) committed
      Class space:        1.00 GB reserved,      18.25 MB (  2%) committed
      Class space:        1.00 GB reserved,      25.38 MB (  2%) committed
      Class space:        1.00 GB reserved,      59.75 MB (  6%) committed
      Class space:        1.00 GB reserved,      83.88 MB (  8%) committed
      Class space:        1.00 GB reserved,     147.50 MB ( 14%) committed
      Class space:        1.00 GB reserved,     188.50 MB ( 18%) committed
      Class space:        1.00 GB reserved,     221.38 MB ( 22%) committed
      Class space:        1.00 GB reserved,     247.62 MB ( 24%) committed
      Class space:        1.00 GB reserved,     326.88 MB ( 32%) committed
      Class space:        1.00 GB reserved,     430.88 MB ( 42%) committed
      Class space:        1.00 GB reserved,     489.50 MB ( 48%) committed
      Class space:        1.00 GB reserved,     584.12 MB ( 57%) committed
      Class space:        1.00 GB reserved,     652.25 MB ( 64%) committed
      Class space:        1.00 GB reserved,     721.12 MB ( 70%) committed
      Class space:        1.00 GB reserved,     767.75 MB ( 75%) committed
      Class space:        1.00 GB reserved,     822.62 MB ( 80%) committed
      Class space:        1.00 GB reserved,     874.12 MB ( 85%) committed
      Class space:        1.00 GB reserved,     926.88 MB ( 91%) committed
      Class space:        1.00 GB reserved,     976.12 MB ( 95%) committed
      Class space:        1.00 GB reserved,       1.00 GB (100%) committed
      ***OOM***
 ```

let me know if there is any additional info that I can provide

**Comment by jbarr21** [comment]
Git bisected down to #910

Potentially related to [KT-56093/Metaspace-leak-in-a-Gradle-plugin-built-with-Kotlin-1.8.0](https://youtrack.jetbrains.com/issue/KT-56093/Metaspace-leak-in-a-Gradle-plugin-built-with-Kotlin-1.8.0)

**Comment by Bencodes** [comment]
> Git bisected down to #910

We haven't switched internally yet, so haven't been able to see if this impacts us. Have you been able to figure out what in Kotlin 1.8 is causing the OOMs?

**Comment by jbarr21** [comment]
the linked youtrack provides the [context](https://youtrack.jetbrains.com/issue/KT-56093/Metaspace-leak-in-a-Gradle-plugin-built-with-Kotlin-1.8.0#focus=Comments-27-6799166.0-0). it looks like [the fix](https://github.com/JetBrains/kotlin/commit/724ccdcadb2312745723fc8b8cae1f77761a49b6) has already been committed and hopefully be included in the next patch release

**Comment by Bencodes** [comment]
https://github.com/bazelbuild/rules_kotlin/pull/932

**Comment by jbarr21** [comment]
Kotlin 1.8.10 resolved the issue
