### ISSUE TITLE
`_run_kt_java_builder_actions` attempts to index empty sequence

### ISSUE THREAD

**Issue by avarun42** [bazelbuild/rules_kotlin#931]
Discovered an issue when attempting to update to `v1.8-RC-1` — if there are annotation processors but `java_infos` is empty, the attempt to dereference index 0 of the list of `class_jars` fails [here](https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/jvm/compile.bzl#L752).

```
Traceback (most recent call last):
	File "/home/runner/.cache/bazel/_bazel_runner/2e09d596b966b017ceca1b8a16be107a/external/io_bazel_rules_kotlin/kotlin/internal/jvm/impl.bzl", line 262, column 44, in kt_jvm_junit_test_impl
		providers = _kt_jvm_produce_jar_actions(ctx, "kt_jvm_test")
	File "/home/runner/.cache/bazel/_bazel_runner/2e09d596b966b017ceca1b8a16be107a/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 493, column 50, in kt_jvm_produce_jar_actions
		outputs_struct = _run_kt_java_builder_actions(
	File "/home/runner/.cache/bazel/_bazel_runner/2e09d596b966b017ceca1b8a16be107a/external/io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 752, column 97, in _run_kt_java_builder_actions
		ap_class_jar = [jars.class_jar for outputs in outputs_list for jars in outputs.jars][0],
Error: index out of range (index is 0, but sequence has 0 elements)
```

**Comment by restingbull** [comment]
* Do you have a quick repro case?
* What version of bazel are you using? (Part of the joy is that this code covers several bazel versions.)

**Comment by avarun42** [comment]
Bazel version is `5.3.0`

**Comment by avarun42** [comment]
Also occurs on Bazel `5.4.0` as well
