### ISSUE TITLE
rules_kotlin is failing with Bazel release 6.1.1

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_kotlin#994]
https://buildkite.com/bazel/rules-kotlin-kotlin/builds/3433#01898f8b-ea3f-4991-97c7-143cc452b611

Platform : Windows, MacOS, ubuntu

Logs
```
SEVERE: ERROR: unexpected exception
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: bazel-out/k8-fastbuild/bin/libKtAndroid/my_kt_kt-kapt-generated-stub.jar
	at io.bazel.kotlin.builder.tasks.jvm.JdepsMerger$Companion.readJarOwnerFromManifest(JdepsMerger.kt:54)
	at io.bazel.kotlin.builder.tasks.jvm.JdepsMerger$Companion.merge(JdepsMerger.kt:99)
	at io.bazel.kotlin.builder.tasks.jvm.JdepsMerger.execute(JdepsMerger.kt:153)
	at io.bazel.kotlin.builder.tasks.MergeJdeps.invoke(MergeJdeps.kt:28)
	at io.bazel.worker.PersistentWorker$workTo$1.invoke(PersistentWorker.kt:97)
	at io.bazel.worker.PersistentWorker$workTo$1.invoke(PersistentWorker.kt:97)
	at io.bazel.worker.WorkerContext$TaskContext.resultOf(WorkerContext.kt:128)
	at io.bazel.worker.WorkerContext.doTask(WorkerContext.kt:156)
	at io.bazel.worker.PersistentWorker$start$1$1$producer$1$1.invoke$lambda$0(PersistentWorker.kt:70)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.NoSuchFileException: bazel-out/k8-fastbuild/bin/libKtAndroid/my_kt_kt-kapt-generated-stub.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1273)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:747)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:864)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:262)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:321)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:287)
	at io.bazel.kotlin.builder.tasks.jvm.JdepsMerger$Companion.readJarOwnerFromManifest(JdepsMerger.kt:44)
	... 14 more
(04:07:53) INFO: Elapsed time: 20.476s, Critical Path: 1.59s
(04:07:53) INFO: 656 processes: 594 remote cache hit, 62 internal.
//app:force_build_apks_test                                           NO STATUS
//libKtAndroid/src/test/java/examples/android/lib:SomeTest      FAILED TO BUILD
```

Steps:
```
git clone https://github.com/bazelbuild/rules_kotlin.git
export USE_BAZEL_VERSION=6.1.1
cd examples/android
bazel test //...
```

CC  Greenteam @fweikert

**Comment by sgowroji** [comment]
Closing this issue as we are seeing the above pipeline green now.
